### ISSUE TITLE
Running locally in Windows

### ISSUE THREAD

**Issue by geekyayush** [schul-cloud/jitsi-deployment#13]
Hello,

I'm trying to run this locally in windows.
I have **Kubernetes v1.16.5** running using Docker Desktop.

After cloning the repo, setting up username, password in **bbb-basic-auth-secret.yaml** and jitsi credentials in **jitsi-secret.yaml**, I have been getting this error

![j8Oq5PA](https://user-images.githubusercontent.com/25874080/84376214-64d5d680-abfe-11ea-9496-64b7791c6396.png)

So, what can I do regarding this error?

If anyone could help me out with this, I'd highly appreciate it.

Another question that I have is, how can I access it after successfully running it?
What I mean is, on which port I can access the jitsi web?
e.g. localhost:80 ? or localhost:8443?

Thank you
Ayush.

**Comment by wolfm89** [comment]
Hi Ayush,

Let me clarify a few things:
- We tested our setup against Kubernetes v1.17.2 and v1.17.6, so maybe you will run into issues regarding your v.1.16.5 cluster
- All files named `bbb-*` are not necessary for this setup as they are just there to set up monitoring of an affiliated project (https://github.com/schul-cloud/bbb-deployment). You can delete them and remove them from your `kustomization.yaml` files. I have also added this explanation to the readme now (on the dev branch).
- I highly doubt that it is easily possible to run this setup on a local machine. For example we use services of type `LoadBalancer` which are typically handled by your Cloud provider. Another problem you will run into is lacking resource requirements. If you take a look at the minimal resources required for this setup (checkout the Deployments, StatefulSets and DaemonSets) you will realize that this setup is too heavy for running even on a high end PC. One more problem you will face is the fact that our setup uses a public domain. You will have to adjust the ingresses to serve from local.

Nevertheless, regarding your error: Where do you see this error? When you apply the manifests? Or in the logs of a certain container? It seems like your container cannot resolve the cert-manager webhook.

If you really manage to run this setup locally I'd appreciate any valuable input about how to get it up and running.

Jitsi will be available through the HAProxy Ingress (HTTPS/443).
