### ISSUE TITLE
Jitsi related Pods should have liveness/readiness checks

### ISSUE THREAD

**Issue by wolfm89** [schul-cloud/jitsi-deployment#5]
We currently don't have liveness/readiness checks for the `prosody` and `web` pods.

I suggest to use the return value of `prosodyctl status` to gain confidence in the prosody readiness.
For the `web` pod I suggest to just use the HTTP port and check for a successful query.

**Comment by mvakert** [comment]
ReadinessProbes for `prosody` and `web` deployment are established. Your recommendations have been used. In fact `prosodyctl status` returns a 0 code if and only if prosody is running correctly, see https://github.com/bjc/prosody/blob/master/prosodyctl. The use of liveness checks should be discussed further.
