### ISSUE TITLE
Monitoring for Prosody

### ISSUE THREAD

**Issue by wolfm89** [schul-cloud/jitsi-deployment#7]
In order to collect statistics about Prosody an [additional module](https://modules.prosody.im/mod_prometheus.html) has to be installed that serves the statistics in Prometheus format at an HTTP endpoint.

**Comment by mvakert** [comment]
Done. However, statistics do not offer much information of use by default, as they mostly display metadata about the communication between the Jitsi components. 
The statistics offered by the HTTP endpoint can be extended using [Prosody plugins](https://modules.prosody.im/) . Especially those starting with `mod_measure` could be interesting. We have tested the plugins [mod_measure_stanza_counts](https://modules.prosody.im/mod_measure_stanza_counts.html) (collecting stats about the stanzas which are exchanged by the components) and [mod_measure_client_presence](https://modules.prosody.im/mod_measure_client_presence.html) (collecting stats about the participants). 
Most of the modules are not documented (well), and partly old. We also tried to install the plugin mod_statistics, which did not work, as a dependency throws an error.  
Using those packages, we see four different kind of stats: 
1. prosody_mod_muc: Counting in some way, if Multi-User-Chatrooms (MUC) are found or not by the components. Not documented (or at least documentation not found) how these numbers arise. Available by default.
2. prosody_stanza: Collecting numbers on the stanzas the compnents exchange. Not document how these numbers arise. Availabe through the plugin mod_measure_stanza_counts 
3. prosody_stats: Possibly metadata on how much time is necessary to collect the stats. No documentation found. This [file](https://hg.prosody.im/prosody-modules/file/tip/mod_stats39/README.markdown) might give some indication for that. Availabe by default.
4. prosody_client_presence: Collecting numbers of the clients, which are present. Is availabe if plugin mod_measure_client_presence  is installed.

Additionally, memory and CPU usage can be reported (using [mod_measure_memory](https://modules.prosody.im/mod_measure_memory.html), [mod_measure_malloc](https://modules.prosody.im/mod_measure_malloc.html), [mod_measure_cpu](https://modules.prosody.im/mod_measure_cpu.html) ). However, we collect them already with our Prometheus-Kubernetes setup.
